version: '3'
services:
  app:
    container_name: app
    build: ./dist
    image: prod-image-tag
    ports:
      - "9000:9000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .mongodb:/data/db
